# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Safari
version:      0.02
version_from: lib/Net/Safari.pm
installdirs:  site
requires:
    Class::Accessor:               0
    Class::Fields:                 0
    Data::Dumper:                  0
    LWP::UserAgent:                0
    Test::More:                    0
    Test::Simple:                  0.44
    URI::Escape:                   0
    XML::Simple:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
